### ISSUE TITLE
Slow Response Rate and Delayed Risk Graph Updates in OptiTrade Tool

### ISSUE THREAD

**Issue by hash123shaikh** [charmtraders-apps/issue_tracker#6] opened 2024-02-13 08:07 UTC
**Summary:**
Experiencing significant delays in the display refresh rate, notably when performing actions that require dynamic graphical updates, particularly during the animation or data refresh in the risk graph section.

**Steps to Reproduce:**
1.	Open the OptiTrade tool and navigate to the risk graph section.
2.	Select a trading strategy for evaluation and initiate the risk graph animation.
3.	Observe the time taken for the graph to refresh or for the animation to proceed to the next frame.

**Expected Behavior:**
The risk graph and other graphical elements of the tool should be updated promptly in response to user actions, with minimal delay, to facilitate smooth and efficient analysis.

**Actual Behavior:**
There is a noticeable lag between initiating an action (like starting the risk graph animation) and seeing the result on the screen. The risk graph, in particular, takes an extended period to refresh or move to the next frame during animation, hindering real-time analysis.

**Frequency:**
The issue occurs consistently across multiple sessions and does not appear to be tied to specific conditions or one-time occurrences.

**Environment:**
•	Operating System: Windows 10 Pro, Version 22H2
•	Processor: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
•	RAM: 8.00 GB
•	System Type: 64-bit operating system, x64-based processor

**Comment by charmtraders-apps** [comment] 2024-02-18 16:30
Thank you for bringing this issue to our attention and providing a detailed description of the challenges you're experiencing with the refresh rate during dynamic graphical updates in the risk graph section of the OptiTrade tool. Your thorough account, including the steps to reproduce the issue and the environment details, is invaluable to our investigation.

We are actively investigating the matter to identify the root cause of the delay you've encountered. We understand how crucial a seamless and responsive interface is for efficient analysis and decision-making.

It's important to note that the generation of backtesting graphs, particularly those involving complex animations or data refreshes, is a process that demands significant computational resources. These operations are both CPU and I/O intensive due to the large volumes of data being processed and rendered in real-time.

In our system architecture, priority is given to live data processing to ensure the most current information is available for trading decisions, as timeliness is critical in these contexts. Consequently, tasks such as backtesting graph generation, where immediate completion is less critical, may experience lower prioritization. This approach is designed to optimize overall system performance and ensure the highest level of service during live market operations.

We recognize the importance of the backtesting feature and are committed to enhancing its performance. Our team is exploring various optimizations and solutions to reduce delays and improve your experience without compromising the quality and accuracy of the data presented.

We appreciate your patience and understanding as we work on these improvements.

**Comment by charmtraders-apps** [comment] 2024-02-25 10:49
Optimized risk and performance chart speed by selectively loading relevant option chain data, reducing load time.
Implemented in release: 24.02.02 beta

**Closed as completed by charmtraders-apps** 2024-02-25 10:49 UTC
